
// This file is dynamically generated and will be replaced by the build process.
// Do not edit this file directly.
// It is used to configure the Firebase SDK.

declare const firebase: any;

const firebaseConfig = {
  apiKey: "AIzaSyDLAy94tcrBKrzdufeLRBEn71pUXFMqmyk",
  authDomain: "a-z-premium-app-store.firebaseapp.com",
  databaseURL: "https://a-z-premium-app-store-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "a-z-premium-app-store",
  storageBucket: "a-z-premium-app-store.firebasestorage.app",
  messagingSenderId: "1056127403780",
  appId: "1:1056127403780:web:dd8167ed4ad12e5c117251",
  measurementId: "G-22LE00THNP"
};

if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
}

export const db = firebase.database();
